language: java

notifications:
  slack: jfixtures:jOwrd0VAUWmsEqAMtfwqOM9J
  email: false

env:
  global:
    # OSSRH_JIRA_USERNAME
    - secure: "mzj6ay47cDPVUfyiYNopR7QF6vjYZYEJSItFMBAub9zsxix/oPePJLycuuwMAGWalAd2skpNECnNpONRvN5pXzI0uCU/efGUGjyGvPof6KDnm/fx+YCDWWT6V9v2MOqkIXPx+/5Cy52Pz07O2udbDTtePsA15xILm/h+Q/sSZk1aTX6H5F5JjUnv0s+13aaJzxeU/3EQsRf77eQArT5jDhWTTnQSZROsSdk9fYZNmzltYimQCiLELkCHLu2Q5vYsyACe3m10oE4Mw2nEJrz4pz0OHAyhsn/8NUjMHaYKUzVQoDs0wmLETLJlZ5DFf+ELB0jxtCLZW4dmARogRCziVMNTVhcp0ZOvV1bu0JwN84wZmxMsd1p0i9/+8TQRXwLZBhwjZx9Cs3txi8Hc5MElZBYdX13bfEh6VE2PBzOZ3VGsWU+XiLIMUAZPSTzIuA20EWI33v3ni2oxP9+HcimH9za4mFvrmPiYtydhpvj/UsyX7chyNHO6e5TJYUF5K/putbUSdjsJjMHgKGQWwfssluFPBoKqfW/w34+PS9JXoK56uupWGaZNa9awD3pKyBIKqTPyfyD3TyZEPHepzhsDwtBQ63wMgNOtUoGg26RkYPXM9+agVGnjW3KBIk2RCVVwkbdZqLC+0dPNxYdUn7lEKc0v5TrYh03hYFvzgrQF/Fw="

    # OSSRH_JIRA_PASSWORD
    - secure: "RVafRlD32xx1VVSvRoNGlbbl6DUkg/r5ebWV7eUna+I3pDYWzWNRTj4ExnniiczXvISaMfFm6IVBoadoYe79NMY24C18JgG8JCKD2/IWT4w39rVWq93c5SFQgGAvUL2cC+wDhjoPGVq8r3sNW2qNuLZFVTBUFhsekxmBedwBFPEDcaoUjmMYT0NSFimu7/ZWFnd6ajJNdKNEyZV3E9+m8AzYGblG3OQF440BQfk3Yj52rlwXctnttOWVzSIN4qwZgepOJIrro8BspmzwlhQ1bDKt9E5u3/ge4mH2BhNOm0zp6Yptw+Q8A8Vcn2CuQ24ELbi95dKRqKB2h+SEWqkh8B6X21JMmQEu5B4qpWaiCsmCJC2vdPxt/JAHfk+Nt3/WDQHt3eHbuYnGvgxW6AB79SnLjsgcdUBBIIYX20SsizCZlKn+w65WXAvNtJHQCVdKt+A8vZXP7Srgkr1bIH9Qgv/LfPJuoUuEDDzcB1uBLgLdXDrcjMZmW6hYnQGuj2Gm1F6ypm7UIGiaW+fAmEgS0N2c0gr8yu/hhlhU3ZKIjcaxXDkkJjxKdtPm6EbWj8x4ozWOAs8rgqzlG1PRZQf/F5Z6gMs4pDC0TqfC08oX5xq5GITdvVm0QMCT+eIVBoWguQ2c8ZH2gE7pxdQPUAKlgleoioGht5f0Q5ZEPxIfYW8="

    # GPG_KEY_NAME
    - secure: "eAZudMPnongBpLWlxDwTHT51RaaYUCOcwzu76SoT7IXUb5JUHGgUWUkWuabrpAJ1ARPE9h0Ang0uav6Fb9jR7IRalIatnBTWG6Z1+XZyQFzMchw9olfaupQKqYH23ZISM5a590pMCPtx3flttWbBKeSQN+4FKYjreY3pKvNxPYJJH/K6CmAMWptc/cbwAsoEVV40yHTgZL12XhP6LearUp0wJ2Ax/PTgX2JZT/BL3lqOUH1DcDDyvh67zGASkF2jGHP3LDtxWerQMDdEJHNRsGNlrOqn6U8SFV4pZLV8Ekp2oBt+wAN4WmcWz6Gf0yxmvteh0jNIorn9BGBKNMQcFWOQ7yojjPzx95393Wxrg8JmlvXkIixwdwYY2aClT5VPDePmMIJJdr3KVkUoipHPBXp1z9ByQ/ZJa0OSBagUWcyX6P8F9ALnw9vNfp81i1nEFPOcACGgwD6TEh8etOEqpzDzMAhur60bQMuDdWROXkhfOgKSfzGIcEBKULGPefU6NIiJC1idPQ5+8rpjkOpLOG1PlUF1sXs23ih+5qUSdsYJhzpZMaxGrYBUv0OeIhH7O2c8X7EH2LZcYjPi53snhOpgFOTli19vx/8teoMU2S6QtoxCU0J9st40penm+hl4tdJBBoPHaaNxzXyyOk9+APHs33FMd96vpF2l0MkGZ94="

    # GPG_PASSPHRASE
    - secure: "VlJRGaUUwj8aO3/o68m3rRloMJ9kMXYKlr5CNhtfVFPIa3hSB+FQ5pDjhvJ6VVww8t0o2vo1lgLkuXvAP8i4Z3OSCZn7+FSUk2iUX/rimC+zEJ2WBkgOrUk20X8kTjCHAAlggP3Ifu9RksjobaZr7ZJKEgGfXXSOZY8Qacc429+vfgZXZnG+nNSnzx3ba0Nzc5MJexse4HQz7Whjz463MVQ3RUTMWAoSkvFq7KNE/tlhLCgcNGzwtlEGzoO1fXT+de6GMer31uFbx84IPlrBsLluYeh29ZtiA9asragzaN0oEcM5yl3un44CKhEDRP0dPafGD7OOCbH9iw7K5+100SESWTbtvtmBf6cGX8Sd/Dm74lCEYsCjEwogbDzlTPEha1BFO1/tsCnswaBqcPIy2SxSEVJNeIC/Cg5o5+tIAq9N8ZM3th4I1uYvNk/6tii45D6OjAD/gnFZcM0tcAT/tKvQCuqElo2LezqCEBBUU9fcXhijTug+Eb2Hk2/NqIq2BLXt1VxBqNBvVdwGSUs405zEYPlkxDcL6Z2nvWkS52Q59t6o7aKPPWp8XGpVsNlbKcQykP6J2s6YttFcd86LrJwWt4AGT/17q3Kx5PbaYGQsIVfEXnosxrRHQqJv8QmpX5LccUI/oOZC/BF48Oc+ePfXA/pWpkMTUxvgBVZig6Y="


jdk:
  - oraclejdk8


before_install:
  - openssl aes-256-cbc -K $encrypted_732fa8d9783d_key -iv $encrypted_732fa8d9783d_iv -in delivery/codesigning.asc.enc -out delivery/codesigning.asc -d
  - gpg --fast-import delivery/codesigning.asc


cache:
  directories:
    - $HOME/.m2/repository/
    - $HOME/.m2/wrapper/


after_success:
  - chmod +x delivery/deploy.sh
  - ./delivery/deploy.sh
